[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid
childlogdir=/var/log/

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
startretries=5
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

# # El frontend es servido estáticamente por NestJS/Nginx, no necesita un proceso separado.

[program:nestjs]
# Ejecuta directamente el archivo compilado para evitar que npm
# intente volver a compilar en tiempo de ejecución.
command=node dist/main.js
directory=/app/backend
autostart=true
autorestart=true
startretries=5
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
# Se usa 'PORT' en lugar de 'NESTJS_PORT' ya que NestJS por defecto busca 'PORT'
environment=NODE_ENV="production",PORT=3001
