events {}
http {
    include mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    upstream backend_service {
        server 127.0.0.1:3000; # NestJS backend
    }

    upstream frontend_service {
        server 127.0.0.1:3001; # Next.js frontend
    }

    server {
        listen 80;
        server_name localhost;

        # Redirige el tráfico /api/ y /webhooks/ al backend
        location ~ ^/(api|webhooks)/ {
            proxy_pass http://backend_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Redirige todo el tráfico restante al frontend
        location / {
            proxy_pass http://frontend_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}